=== Alcel/AccesoADatos/AccesoADatos/src/datos/biblioteca.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Declaración de un tipo de dato ENUMERADO -->
 
  <xs:simpleType name="tipoSexo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="masculino"/>
      <xs:enumeration value="femenino"/>
    </xs:restriction>
  </xs:simpleType>

<!-- Declaración del elemento raíz -->

  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string" />
              <xs:element name="subtitulo" type="xs:string" minOccurs="0" />
              <xs:element name="coleccion" type="xs:string" minOccurs="0" />
              <xs:element name="autores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="autor" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="sexo" type="tipoSexo" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="genero" type="xs:string" />
              <xs:element name="editorial" type="xs:string" />
              <xs:element name="precio">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:double">
                      <xs:attribute name="moneda" type="xs:string" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="paginas" type="xs:string" minOccurs="0" />
              <xs:element name="tema" type="xs:string" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="isbn" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Alcel/AccesoADatos/AccesoADatos/src/datos/biblioteca.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd">
	<libro isbn="978-84-09349-7">
		<titulo>Los renglones torcidos de Dios</titulo>
		<autores>
			<autor sexo="masculino">Torcuato Luca de Tena</autor>
		</autores>
		<genero>novela</genero>
		<editorial>Austral</editorial>
		<precio moneda="euro">9.80</precio>
		<paginas>440</paginas>
		<tema>Una novela honesta sobre la locura, que sigue manteniendo intacta su vigencia</tema>
	</libro>
	<libro isbn="978-84-96981-11-9">
		<titulo>La asertividad para gente extraordinaria</titulo>
		<autores>
			<autor sexo="femenino">Eva Bach</autor>
			<autor sexo="femenino">Anna Forés</autor>
		</autores>
		<genero>autoayuda</genero>
		<editorial>Plataforma</editorial>
		<precio moneda="dolar">15.25</precio>
		<paginas>275</paginas>
		<tema>Con este libro, las autoras nos regalan un tratado esencial sobre comunicación y relaciones humanas</tema>
	</libro>
    <libro>
        <titulo>La catedral del mar</titulo>
        <autores>
            <autor sexo="masculino">Ildefonso Falcones</autor>
        </autores>
        <genero/>
        <editorial>Grijalbo</editorial>
        <precio>15.4</precio>
    </libro>
    <libro>
        <titulo>El ocho</titulo>
        <autores>
            <autor sexo="femenino">Katherine Neville</autor>
        </autores>
        <genero/>
        <editorial>Debolsillo</editorial>
        <precio>2.1</precio>
    </libro>
    <libro>
        <titulo>Conversaciones sobre la república</titulo>
        <autores>
            <autor sexo="masculino">Julio Anguita</autor>
            <autor sexo="femenino">Carmen Reina</autor>
        </autores>
        <genero/>
        <editorial>El páramo</editorial>
        <precio>15.95</precio>
    </libro>
    <libro>
        <titulo>El gran diseño</titulo>
        <autores>
            <autor sexo="masculino">Stephen Hawking</autor>
            <autor sexo="masculino">Leonard Mlodinow</autor>
        </autores>
        <genero/>
        <editorial>Crítica</editorial>
        <precio moneda="dolar">5</precio>
    </libro>
	<libro isbn="84-415-1576-X">
		<titulo>XML</titulo>
		<coleccion>Manual imprescindible</coleccion>
		<autores>
			<autor sexo="masculino">Juan Diego Gutiérrez Gallardo</autor>
		</autores>
		<genero>informática</genero>
		<editorial>Anaya multimedia</editorial>
		<precio moneda="euro">24.7</precio>
		<paginas>350</paginas>
		<tema>Una aproximación muy general, pero directa, al lenguaje XML</tema>
	</libro>
</biblioteca>
